version: '2.1'
services:

  exred_tests:
    build:
      context: .
      dockerfile: Dockerfile-exred
    privileged: true
    working_dir: /usr/src/app
    command: ./docker/cmd-exred.sh
    env_file: ./docker/.env
